### ISSUE TITLE
Batur

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#32] opened 2021-02-05 18:02 UTC
@m-schoettel, 

In Batur.xml, I have closed the second `<foreign>` tag for ```<lb n="Ar4" break="no"/><supplied reason="lost">ra rakryan apatiḥ riṁ</supplied> jaṅgala kaḍiri, mpu mada, <foreign xml:lang="san-Latn">raṇa-maddhyāryy-anukūla-karaṇa</foreign>, <foreign xml:lang="san-Latn">para-sainya-śiraḥ-kapāla-gan<unclear>v</unclear>otpāna <!--em. something here, either utpāda or utpanna, and garva/gardha (pride, arrogance?)-->ma```
Can you check that I have closed it at the right place? 

Thanks

**Comment by arlogriffiths** [comment] 2021-02-27 07:33
@m-schoettel : why haven't you reacted?

**Comment by m-schoettel** [comment] 2021-02-27 11:51
I am not really sure myself whether this Sanskrit compound ends with -otpāna and another starts with ma(...), or if it is one long compound beginning with raṇa-maddhyāryy- and straddling the line boundary. Maybe the second option is the most likely.

So it was hard to decide which place is the "right place" to close the foreign tag. The problem is that several syllables are missing at the beginning of l. 5, which makes the interpretation difficult for me. 

I have tried to solve this in any case. Yet, the file still does not validate.

**Comment by arlogriffiths** [comment] 2021-02-27 12:59
Thanks Marine. The current validation problem is the same one as the one raised in #34, unrelated to the issue raised here by Axelle. So I am closing this issue.

**Closed as completed by arlogriffiths** 2021-02-27 12:59 UTC
Labels: bug, review
